image: node:16.15.0

cache:
  paths:
    - node_modules/

stages:
  - test
  - lint
  - deploy_production

include:
  - template: Code-Quality.gitlab-ci.yml

eslint:
  stage: lint
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js .

deploy_production:
  stage: deploy_production
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools@11.13.0
    - npm install
    - npm run build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
