image: node:16.15.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g firebase-tools@11.13.0

stage:
  - lint
  - deploy_production

eslint:
  stage: lint
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js .

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install
    - npm run build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
