image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm i -g firebase-tools

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install
    - npm run build
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
